### ISSUE TITLE
Visual fixes for resource pages

### ISSUE THREAD

**Issue by Danwhy** [TheScienceMuseum/collectionsonline#106]
* [x] - Which attributes to use as facts at the top of the page?
* [x] - Which attributes to use as details at the bottom of the page?
* [ ] - What to display when there are no details/facts/description?

**Comment by jamieu** [comment]
See Missing values on object page #120

**Comment by Danwhy** [comment]
* [ ] Makers
* [ ] Credit
* [ ] Measurements
* [ ] Type
* [ ] Taxonomy

**Comment by jamieu** [comment]
Toby made a **very basic** design for a 'no result' page, not sure if it got copied over from the codesign repo.
/noresults.html

* probably needs some some additional work / revisiting

**Comment by jamieu** [comment]
We've just been discussing the archive / document icons and think we'd prefer to use the 'graphical text' as per the objects.

We should use the 'extent' field (on documents) for this text.

btw. just to clarify:

- archive = the top level 'fonds' records (this is itself a 'document' record, we're just treating it as a special one)
- document = everything else (which can include series, sub-series, folders and the records that actually represent a single document). 

note 1: _we may in future represent the folders & series that sit between the top level 'fonds' record and the leaf node records/documents that sit at the bottom of the tree slightly differently. But for now we're treating everything bar the top-level record as a 'document' with a document icon (even if they in represent a record that could have multiple scanned documents attached to it or sub-folders)._

note 2: _I am asking Toby to design us a new top level icon to represent the 'fonds' or 'archive' record #125 but hopefully this will just be a case of switching the 'archive' icon in the CSS_

Jamie

**Comment by tobystokes** [comment]
Yes agree that may look better. Ideally, given that there aren't that many top level archives, if we could assign them a picture to represent, that would be worthwhile.

**Comment by jamieu** [comment]
@tobystokes yes that's what we're gonna try and do, there a small enough set of them that even Emily and I could pick assign sensible images for them all.

**Comment by jamieu** [comment]
A couple more changes, I have [updated the wiki to reflect the additions](https://github.com/TheScienceMuseum/collectionsonline/wiki/Values-to-display-on-HTML--pages#peopleorganisation-page), but changes / deletions below:

## Object

**Changes:**
- Change the title to use `title.value` rather than `summary_title`

## Person/Organisation template

**Remove:**
- taxonomy

**Comment out:**
- **the image** (we'll add the images back in if we can figure out how to sensible/reliably assign them; but unlikely to have solved that in the short term and in the mean time want to demo without the Babbage picture hard coded in)

**Additions:**

See wiki page for fields / additions to People/Org page
https://github.com/TheScienceMuseum/collectionsonline/wiki/Values-to-display-on-HTML--pages#peopleorganisation-page

### Person variant 

`"sub_type": ["person"]`

<img width="855" alt="individual" src="https://cloud.githubusercontent.com/assets/91365/16521823/6b9a8d68-3f91-11e6-8cb9-c2903838a08f.png">

### Organisation variant

`"type.sub_type": "organisation"`

* `name.value` `lifecycle.birth.date` `lifecycle.birth.date` (name normalised/reversed on comma, date in smaller font)
* INDUSTRY: `occupation` _(split on semicolon)_ 
* LOCATED: `lifecycle.birth.location`

<img width="552" alt="organisation" src="https://cloud.githubusercontent.com/assets/91365/16522460/d352bc6a-3f95-11e6-8832-e0b972eae9dd.png">

**Comment by Danwhy** [comment]
Remaining points moved to sprint 3: #164, #159
