### ISSUE TITLE
Nested 'place of origin' no longer working for multiple selections

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1080]
ie. select United Kingdom then select London:
http://localhost:8000/search/places/united-kingdom+london

**Comment by SimonLab** [comment]
The issue is due to the following function: https://github.com/TheScienceMuseum/collectionsonline/blob/master/lib/helpers/utils.js
```
module.exports = {
  uppercaseFirstChar: function (str) {
    var exclude = ['and'];
    if (!str) return false;
    return decodeURIComponent(str).split(/[\s-]/g).map(e => {
      if (exclude.indexOf(e) === -1 && e !== '') {
        return e[0].toUpperCase() + e.substring(1);
      } else {
        return e;
      }
    }).join(' ');
  }
};
```
This function will `uppercaseFirstChar` of a string (e.g: `hello there` will be `Hello There`).
However when multiple filters are selected the function is applied to an array instead of a string. The array is converted to a string with `decodeURIComponent(str)` (e.g: `["hello", "there"]` becomes `"hello,there"`) and we lost the array type which is used in Elastsicsearch to filter on multiple terms.

So we need first to check the type of the parameter, if it is a string we can apply directly the function but if it is an array we need to apply the function for each element of the array
