### ISSUE TITLE
Check Boolean logic in search queries

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1120]
Doesn't seem work, either NOT or `-`

Allow boolean questions ie. "This NOT that" and  exclude "this string"

https://collection.sciencemuseum.org.uk/search/images?q=rocket%20not%20Stephenson%20

**Comment by SimonLab** [comment]
I've checked how we build the query on Elasticsearch and we are already using the `query_string` (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html), see https://github.com/TheScienceMuseum/collectionsonline/blob/f605917a424044c200de04ce02e71b63ac6a4bd0/lib/search.js#L30-L38

I think the text analyser might create a slight difference when the logical "operators" are in lowercase or uppercase.
For example if the search is [rocket NOT Stephenson](https://collection.sciencemuseum.org.uk/search?q=rocket%20NOT%20Stephenson) the results list seems to be better:
![image](https://user-images.githubusercontent.com/6057298/54981351-ff1d1080-4f9f-11e9-846b-85890956e625.png)

We can still see that the fourth result is `Model of Stephenson's Rocket ` and I think it's because the title contains directly the term "rocket", however we can specify the query for example with [rocket NOT stephenson NOT model](https://collection.sciencemuseum.org.uk/search?q=rocket%20NOT%20stephenson%20NOT%20model) which returns:
![image](https://user-images.githubusercontent.com/6057298/54981571-82d6fd00-4fa0-11e9-9c8d-9249312ae372.png)

So I think the correct way to use boolean operator with Elasticsearch is to use the uppercase operator and to filter down by creating a more precise query.
Does this makes sense @jamieu ?

**Comment by jamieu** [comment]
Yes, that makes sense!

I did make some changes to the logic last year around this, so it might be
that I managed to fix it back then.
