### ISSUE TITLE
Promo / new theme block for home page

### ISSUE THREAD

**Issue by tobystokes** [TheScienceMuseum/collectionsonline#1157]
a bit like the one on the main site home apge

**Comment by jamieu** [comment]
Hii @tobystokes been thinking a bit more about this, esp. in light of adding a new block at the weekend. I'm wondering if instead of a single big promo block we need to look at:

1) Making the existing box into more of a Carousel so that users can scroll though up top say 12 different promo blocks (like we have now). 

_Question here re. what is out standard usage of arrows on categories (is it like the main Lightbox on record pages) or more like the arrows used on the main site where they sit above the boxes (I am not a massive fan of this but maybe more consistent across group sites)?_

2) Adding in some new 'promo block' that allow the use of textual sub-links under the main category. The obvious would be 'Photography' and then sub links to the various Photographic collections. Ditto. Railway collections: posters, memorabilia, cutlery, timetables etc.

_Could just be 4 simple blocks, or if your feeling creative then some more 'editorial' style layout made up of big and small boxes (ala `[the Grauniad home page](https://www.theguardian.com/uk)` for a common example, but obv. doesn't' need that level of complexity/detail)_

Let me know if you need more examples of copy, but for starters:

**Photographic collections**
* Daily herald
* National Railway Collection 
* Contemporary photography

**Railway Memorabilia**
* Timetables
* [Curiosities](http://collection.sciencemuseum.org.uk/search/categories/miscellanea-&-curiosities/museum/national-railway-museum)
* [Heraldry](http://collection.sciencemuseum.org.uk/search/categories/railway-heraldry/museum/national-railway-museum)  
* [Fixtures and fittings ](http://collection.sciencemuseum.org.uk/search/categories/fixtures-&-fittings-from-railway-buildings/museum/national-railway-museum)
* [Personal Comforts ](http://collection.sciencemuseum.org.uk/search/categories/passenger-comforts/museum/national-railway-museum)

![img-5256](https://user-images.githubusercontent.com/91365/43519548-cd12f0fa-9587-11e8-9746-1ecc19dc4087.jpg)

**Comment by jamieu** [comment]
Looking good a few points of feedback:

**1) Lose the link on the TL Science Museum Group logo**

Lots of discussion re. this one, but feeling is lose it for now as it takes users somewhere we don't want them to go.  _We may resists once we revamp the headers across all sites._

**2) Can we make the spyglass / spyglass <li>'s black or grey, feeling here is the blue looks too much like wikipedia links.**
<img width="1243" alt="spyglass-text-in-black" src="https://user-images.githubusercontent.com/91365/46616696-05fbb800-cb13-11e8-92b2-0ce8c04a2395.png">

**3) Map looks good, but can we make the locations/logos link to the relevant canned 'on display' search.**
<img width="1290" alt="make-map-locations-clickable-and-link-to-on-display-searches" src="https://user-images.githubusercontent.com/91365/46616764-288dd100-cb13-11e8-81c3-d5602aa6dd5a.png">

**4) Some odd wrapping on the highlights when going back/forth to page (basically they stack)**
<img width="315" alt="highlights-odd-wrapping" src="https://user-images.githubusercontent.com/91365/46616902-71de2080-cb13-11e8-86e9-126677b59f6b.png">

**5) Gradient bleed: hard to catch this one in a screenshot, but hopefully you cab see what I mean? It is actually worse in some point than the screenshot**
<img width="869" alt="gradient-bleed" src="https://user-images.githubusercontent.com/91365/46616942-83bfc380-cb13-11e8-8d3d-4b620db2c358.png">

----

### Text for Themes and Highlights

_Still WIP but we're kind of agree on these now, I can update the HTML, but in case you feel like you want some real world text/links._

### Themes

**Medicine**
_into sentence to come_
http://collection.sciencemuseum.org.uk/search/categories/materia-medica-&-pharmacology
http://collection.sciencemuseum.org.uk/search/categories/surgery
http://collection.sciencemuseum.org.uk/search/categories/classical-&-medieval-medicine 
http://collection.sciencemuseum.org.uk/search/categories/therapeutics

**Railway**
_into sentence to come_
http://collection.sciencemuseum.org.uk/search/categories/railway-posters,-notices-&-handbills
http://collection.sciencemuseum.org.uk/search/categories/passenger-comforts
http://collection.sciencemuseum.org.uk/search/categories/photographic-collections-(railway)/images
http://collection.sciencemuseum.org.uk/search/categories/railway-infrastructure

**Art**
_into sentence to come_
http://collection.sciencemuseum.org.uk/search/categories/art
https://collection.sciencemuseum.org.uk/search/objects/object_type/poster (object name query)
https://collection.sciencemuseum.org.uk/objects/co205344/the-photographic-library-of-the-daily-herald-newspaper-1911-1965
https://collection.sciencemuseum.org.uk/search/categories/photographs

**Industrial Revolution**
_into sentence to come_
https://collection.sciencemuseum.org.uk/search/categories/textile-industry
https://collection.sciencemuseum.org.uk/search/categories/textiles-machinery
https://collection.sciencemuseum.org.uk/search/categories/motive-power
https://collection.sciencemuseum.org.uk/search/categories/coal-mining
 
### Highlights

(finding some nice pictures for these now)

- Babbage Papers http://collection.sciencemuseum.org.uk/documents/aa110000003/the-babbage-papers
- Toys & Games https://collection.sciencemuseum.org.uk/search/categories/toys-&-games
- Maths https://collection.sciencemuseum.org.uk/search/categories/mathematics
- Smoking https://collection.sciencemuseum.org.uk/search/categories/smoking
- Television https://collection.sciencemuseum.org.uk/search/categories/television
- X-Rays https://collection.sciencemuseum.org.uk/search/categories/x-rays
- Food and Drink https://collection.sciencemuseum.org.uk/search/categories/food-&-drink-industry
- Astronomy  https://collection.sciencemuseum.org.uk/search/categories/astronomy
- Computing and Data processing https://collection.sciencemuseum.org.uk/search/categories/computing-&-data-processing
- Radio Communications https://collection.sciencemuseum.org.uk/search/categories/radio-communication
- Time Measurement https://collection.sciencemuseum.org.uk/search/categories/time-measurement
- 
-

**Comment by tobystokes** [comment]
You may have seen from recent commits, but FYI:
The map now has rollover states - bear in mind i’d consider the hover text to be ‘inaccessible’ , esp on touch devices.
If the text is supplementary only, might be ok. maybe review after we have real content in there.
I’ve added a sidebar style to the about page. Again, maybe just dump in what might be appropriate content and i can tidy if necessary.
