### ISSUE TITLE
Homepage carousel text overflowing container on mobile

### ISSUE THREAD

**Issue by johnstack** [TheScienceMuseum/collectionsonline#1240]
See image (iPhone SE)
![img_7367](https://user-images.githubusercontent.com/1881723/53261658-7a9f4f80-36cc-11e9-84ff-b7cdbd45b36d.PNG)

**Comment by evancp87** [comment]
This was fixed by Toby on ticket https://github.com/TheScienceMuseum/collectionsonline/issues/1240

I feel that this ticket can be piggybacked on to fix some other bits of CSS that are a bit broken, mainly on the homepage, but elsewhere too

parts list margins/padding is lopsided:
![IMG_4098](https://github.com/TheScienceMuseum/collectionsonline/assets/65721884/1cbf3e68-4b65-4c6b-982d-36d87a3250e0)

SMG Group map causes element to overflow containing block, causing gap to right:
![IMG_4099](https://github.com/TheScienceMuseum/collectionsonline/assets/65721884/865d8ffb-e06b-42c6-bc11-acd547080e28)

Arrows are not aligned:
![IMG_4100](https://github.com/TheScienceMuseum/collectionsonline/assets/65721884/6743f300-5f47-4dce-b770-14168d4ef4db)

Collection dropdown menu appears under open filters:
![IMG_4095](https://github.com/TheScienceMuseum/collectionsonline/assets/65721884/cae59862-eb70-4ae3-adcc-68a1254b468a)
