### ISSUE TITLE
People may never have details - what needs to be done about the UI?

### ISSUE THREAD

**Issue by iteles** [TheScienceMuseum/collectionsonline#159]
![emptydetails](https://cloud.githubusercontent.com/assets/6057298/16688483/2c84bf1a-4516-11e6-92ef-19656c1e381a.png)

**Comment by tobystokes** [comment]
In these cases, can you move the cite block to the right column below related, and then not show the details section?

**Comment by jamieu** [comment]
@tobystokes yes, I think that's the solution!

If we skip the URL field _(which I am happy for us to do)_ then people never have a 'tombstone' details block, which means we van move the cite block to the right column below related.

The only thing we might need to tweak is the colour as otherwise we'll have WoW (...that's a white cite block on a white background, not World of Warcraft!).

- @tobystokes Is it easy to re-jig the template so that the Cite block is on the right, do we need to update the CSS?
- @tobystokes Can we flip the colour of the cite block, so that on People pages it's grey on white.

**Comment by tobystokes** [comment]
* The right column is a `<div class="columns medium-4">` in both locations.
* I'm fairly sure that a `<div class="panel">` like most items in that column, will already change colour depending on it's parents, but let me know if not

**Comment by tobystokes** [comment]
https://github.com/TheScienceMuseum/collectionsonline/blob/master/client/styles/components/_panel.scss#L8-L10
