### ISSUE TITLE
SMG to supply allowed list of relationships and association types

### ISSUE THREAD

**Issue by iteles** [TheScienceMuseum/collectionsonline#160]
This is the list of meaningful associations that will need to be kept in a JSON file and displayed if they are encountered (e.g. son, maker, etc)

**Comment by iteles** [comment]
@jamieu to provide the top 20 temporary ones for now in this sprint (list will need to be modifiable with something like a JSON config file)

**Comment by jamieu** [comment]
We should ideally store these values in a JSON config file so that they can be edited/updated over time/

## Makers

Default to "**Maker:**" (under title) _unless_ relationship is one of the following, 
	
- artist	
- publisher	
- printer	
- photographer	
- designer	
- manufacturer	
- author	
- engraver	
- supplier	
- inventor	
- inventor type	
- patentee	
- modifier	
- illustrator	
- preparer	
- specifier	
- lithographer	
- commissioner	
- issuer	
- creator	
- medallist	
- attributed	
- signatory	
- distributor	
- developer	
- railway company	

## Users

These should appear in the "Related people" block on the right hand side (rather than at the top of the page with makers). They should appear _without_ a relationship label _unless_ the relationship is one of the following, in which case the relationships should appear in brackets after the name.
	
- supplier	
- user
- preparer
- collector
- patentee
- collector
- inventor
- depicted
- sitter
- subject
- owner
- recipient

NOTE: See /objects/smgc-objects-205732 for a good example record:
NOTE: First letter of Maker or User/Association capitalised in all cases.
