### ISSUE TITLE
CO2.0 : Image not fully covering fallback text on EDGE

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1620]
Happy to make the change / test myself if you know what line of CSS need changing. I can probably figure it out, but though you might know immediately what needs adjusting 😄 
![308159107-2e2d8a45-0c12-4e13-a6c6-6dd0f32d6e61](https://github.com/TheScienceMuseum/collectionsonline/assets/91365/6aa2134b-541f-4eaa-a854-96e2fb3761bc)

**Comment by tobystokes** [comment]
is that _all_ search results? (not just the new mph stuff?)

its something something object fit, but could also be a max-width of 100% where the natural size of the image is smaller than the card width here.

**Comment by jamieu** [comment]
Search results, annoyingly I don't have EDGE to hand to test either to see how widespread it is.

But yes, your probably right, not much that can be done,. if the images are the wrong aspect ratio and we don't want to zoom in too much in case it crops others.

Is there an adjustment I can make re. how much we zoom/crop into a image, before giving up?

<img width="736" alt="Screenshot 2024-02-27 at 13 16 06" src="https://github.com/TheScienceMuseum/collectionsonline/assets/91365/d312cfeb-72b3-494b-941f-d10322fd3ac0">

**Comment by tobystokes** [comment]
in that `client/styles/components/_result.scss`try

```scss
@mixin resultclass {
    ...
    img {
        /* remove: width: auto; add below */
        width: 100%;
		max-width: none;
    }
}
```

We do actually have a [browserstack](https://live.browserstack.com) account because its an open source project, i can send you the login, but i _couldn't recreate_ on any of the recent versions of Edge.
it's an evergreen browser now so this might only affect some really old (pre-chromium?) Edges?

If you can get an exact browser version + OS report, that would be great, tell them to visit https://www.whatsmybrowser.org/

**Comment by jamieu** [comment]
Perfect, that fixed it 👍 

Thanks 🙏
