### ISSUE TITLE
Displaying related objects at the bottom of the People page

### ISSUE THREAD

**Issue by iteles** [TheScienceMuseum/collectionsonline#164]

**Comment by Danwhy** [comment]
To get the items related to people I have to make a separate query in elasticsearch for all objects/documents with the person as a user/maker. I'm just trying to work out when the best time to make this query is.

@jamieu Did we want to add these related items to the external api response? If so, I assume we'd have to add a query for the max number of related items to return.

**Comment by jamieu** [comment]
I think we do for the person page, but not for the object page.

In other words a Person should return thier objects/documents as they are
directly related.

But an Object only needs to return itself and its related people. This is
because the related items displayed on an Object page aren't as directly
related / closely coupled - in future we might be able to find direct
children/accessories/parts but for now we'll probably have to just use some
search logic to display what we think are 'related items' to that object,
which only really makes sense on the HTML page/at the presentation layer).
