### ISSUE TITLE
CO2.0: children of children not appearing on SPH record

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1678]
For example part `co8653188` is missing.

https://collection.sciencemuseumgroup.org.uk/objects/co8364603/magellan-1000m-gps-receiver-1990-gps-receiver
https://collection.sciencemuseumgroup.org.uk/api/objects/co8364603/magellan-1000m-gps-receiver-1990-gps-receiver

<img width="705" alt="Screenshot 2024-03-25 at 17 07 26" src="https://github.com/TheScienceMuseum/collectionsonline/assets/91365/b2292aa1-7970-4271-bdff-e3b010173bf8">

**Comment by evancp87** [comment]
Complete. The issue was a defensive check in json-to-html-data.js, which was supressing all nested records, where it just meant to for MPH records. I got around this by supressing nested records by directly using the hierarchy type for MPH. Will need to look into how this works with the new curatorial group, if it will have nested children?

For reference, this is the record that originally had an edge case that the above mentioned defensive check was meant to fix, but introduce another bug - /objects/co205715/the-kodak-museum-collection-collections
