### ISSUE TITLE
Fix portal history / audio player

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1726]
https://collection.sciencemuseumgroup.org.uk/objects/co8085039/behind-the-nhs-poster

**Comment by evancp87** [comment]
This is now fixed. The issue was that there are two AWS buckets which the audio player components point to, depending on whether they are of oral history or audio types. The former seems to have changed in the index, and now returns an audiofile property, which is a direct link, whereas it seems previously the link was built by concatenating the prefix and id. That combo was no longer working, plus seemed unnecessary with the new audiofile link.

Annoyingly, the records with an audio type src in the enhancement block use the old combo, which was also building an incorrect link, so i've added in logic to check for the type and build a link accordingly. I tested it on multiple records and seems to work nicely. The oral history type could be more robust in checking if there is an audiofile property or not and adding a fallback, but as there is only one record with an oral history type (with an audiofile as a property) and no plans to add anymore of those records, it should be fine.
