### ISSUE TITLE
Error when navigating to some records (as opposed to direct linking)

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1747]
**To recreate:**

1/ Go to main search page
https://collection.sciencemuseumgroup.org.uk/search/objects

2/ Click on 'Star Medal' (co415052) (note: error only appears when navigating, direct link is fine)

3/ This error appears 
<img width="1184" alt="Screenshot 2024-05-22 at 12 17 26" src="https://github.com/TheScienceMuseum/collectionsonline/assets/91365/6830388a-8b7e-4507-96a2-a832c7361533">

<img width="471" alt="Screenshot 2024-05-22 at 12 18 43" src="https://github.com/TheScienceMuseum/collectionsonline/assets/91365/f0b3f2e6-4e97-4100-acb0-dcf5a92d07a0">

**Note**: the error only appear when navigating form search results, [directly linking to that page](https://collection.sciencemuseumgroup.org.uk/objects/co415052/1914-1915-star-medal-g-f-w-keen-medal
) works fine, which suggests it problay related to the **/client/ side stuff.**

**Comment by evancp87** [comment]
This is now fixed. It was due to the record's images not having zoom links, which is very rare, and results in the data attributes having "false" instead. The links are passed to handlebars and used conditionally to render ui, the first element being one with an id of "openseadragon-toolbar". In this instance it is never rendered, and osd looks for an element that ends up being null, hence the server error.  I wrapped the openseadragon configuration conditional check to fix this.
