### ISSUE TITLE
Design : Tweak facet filter block

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#244]
Now we have some data in here it’s becoming clear that people are finding it a tad confusing and the active blocks and headers aren't standing out enough. 

Maybe just highlighting the titles for the different facets and the 'clear all' header block (at the top) would solve this confusion.

**Comment by tobystokes** [comment]
Will put some notes here on my expected behaviour (some of which will need implementing by someone else i think). 

## All inactive
By default, all inactive filters should be closed. 
`<div class="filter" />`
If all filters are inactive, the 'Show all filters' at top can also be hidden, so it never has an inactive state.

![image](https://cloud.githubusercontent.com/assets/109024/17898445/b74d90a6-694f-11e6-9763-3ff3d087aba9.png)

## User toggles to open
User can expand filter to see all options
`<div class="filter  filter--open" />`
(non-js fallback - leave all open)
![image](https://cloud.githubusercontent.com/assets/109024/17898858/292f2d8c-6951-11e6-882f-7f9dfa2b11ba.png)

**Comment by tobystokes** [comment]
An alternative to only showing selected categories, etc:

![image](https://cloud.githubusercontent.com/assets/109024/17923935/493af790-69de-11e6-83ed-34da3709b04f.png)

Above the >Other shows currently selected category, but can be expanded to show non-selected filters.

![image](https://cloud.githubusercontent.com/assets/109024/17923985/8feccac4-69de-11e6-8825-89b9ed97586b.png)

'Other' still always constrained by search text. Should probably be only applied to active filters - otherwise likely to produce a mutually exclusive filter, i.e. no results

**Comment by SimonLab** [comment]
`Currently, a selected filter like category hides the other categories - this means that only one category can ever be applied as a filter? I don't think is necessary, unless there is a technical reason for it?`

see #158 We choose to exclude the other filters of the categories if one is selected, the idea is to have a search which reduce the number of results and returns a precise results. Is excluding the other filters still the right solution @jamieu ?

**Comment by tobystokes** [comment]
ok, I see the point of that now. How about my ' > Other categories' toggle suggestion?

**Comment by SimonLab** [comment]
To recap the "other categories" logic: This section show the original list of filters but what happen if a user check one of these filters? Is the new filter selected become the default filter (the other one is unchecked automatically) or is the goal is to have the possibility to select multiple filters (ex: Aircraft propulsion AND Railway Model). If the later I think we will have to rewrite the logic on how we filter to not exclude the filters when one is already selected (#158). We will also need to keep track of all the filters found, currently the list of filters is depending on the list of the results found. Each time a filter is selected the number of results decrease and so the number of filters.

I'm wondering if "other categories" will add more complexity to the facets and will confuse the users. But I'm happy to see how we can implement this logic if we think it will help the users to find the right result.

**Comment by tobystokes** [comment]
My intention was that this was a way of selecting multiple categories (OR)

Though really, my expectation for that (as a user) was driven from their display as checkboxes, which shouldn't be mutually exclusive - I haven't really examined the real life use-case for when more than one category might be a useful feature. So I'll leave that decision to @jamieu .

But my UI concerns could equally be fixed by changing checkboxes to radios, for single-selection state filters like category?

**Comment by jamieu** [comment]
My thinking (and this may differ from yours Toby) is that the filters
should 'drill down' and be based on the values held in the displayed
results set.

So that the only time you see multiple filter values (after
selecting/checking an initial one) is if a object is tagged to multiple
values (ie. 'space' and 'space rockets').

ie. after selecting 'space' you'd either just see that one value (checked)
or if any of the objects tagged to 'space' we're also tagged to other
categories you'd see 'space' (checked) and the other remains values.

(the one exception might be OnDisplay or ImageLicence where there will at
most be ~4 values).

**Comment by tobystokes** [comment]
That makes sense Jamie, and I guess for most filters and use cases, where the facet only has one value, it won't make a difference, or is edge case.

Though I would still say the expected behaviour of a standard checkbox is OR - so maybe I could redesign them to look a bit more ANDy (though can still be checkboxes underneath )

**Comment by jamieu** [comment]
I know we can't fully test either of these yet, but...

In terms of "On display" or "Image licence" I think we should just add in some 'virtual' filters.

**On Display**
- [ ] All museums  <--- this is effectively a 'virtual' category/value that any object on display gets.  
- [ ] Science Museum
- [ ] National Railway Museum
- [ ] National Media Museum
- [ ] MSI Manchester

nb: If a user selects 'All Museums' then the result set should filter to just those objects that are on display. If we are treating 'All museums' as an additional 'virtual' category, then the other values should remain (much the same as is an object had multiple categories or makes).

For 'Image licence' I think we hard code the facet/filter to just have two values, the first 'Non-Commercial ' is any object with an image with a CC licence, the second is any object with an nn-CC image.

**Image licence**
- [ ] Commercial  <-- any image with a CC licence
- [ ] Non-Commercial <-- any image without a CC licence

**Comment by jamieu** [comment]
Re the state of the "[x] close all filters" but at the top when no filterscarecselected.

Could we show pure white block / place holder at top 'on load' so that the filters don't suddenly jump down @tobystokes  is this how you imagined it would work.

**Comment by jamieu** [comment]
Closing, looks much better.

Still think we might want to revisit the 'clear all' button (https://github.com/TheScienceMuseum/collectionsonline/issues/546)
