### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#422]
Can we implement a basic 404 page / route.

@tobystokes let's chat on Wednesday about the actual design / L&F for the page.

_as a second step, we could possible look at offering some smart suggestions based on common URL patterns, particularly those based on previous SMG collection urls. But lets tackle the basics first_

<img width="1125" alt="screen shot 2016-10-05 at 14 46 02" src="https://cloud.githubusercontent.com/assets/91365/19115601/866cdf00-8b0a-11e6-8a31-a7bab2fe2380.png">

**Comment by tobystokes** [comment]
@Danwhy if you or other dwyl'er can set me up with a basic route & template, then I can take it from there?

**Comment by SimonLab** [comment]
@tobystokes I've created a new branch called 404 with a basic [404 error page](https://github.com/TheScienceMuseum/collectionsonline/blob/8f65931ef54bd484074cc97c91a794eb1a3c517b/templates/pages/404.html) that you can modify. Let me know if this is ok.

**Comment by tobystokes** [comment]
Template :thumbsup:

Would there be a way of adding a set of hand-picked record results?
I was thinking of of adding a 'related results' style section, with a few useful collection objects for finding things.

**Comment by SimonLab** [comment]
@emilyfildes do you still want to have a link or an image of this item on the 404 page?
![lost-something-useful](https://cloud.githubusercontent.com/assets/6057298/19520715/144de9be-9609-11e6-9b6d-0643e1c85fec.png)

At the moment the 404 page looks like this:
![404-page](https://cloud.githubusercontent.com/assets/6057298/19520821/6dfc1a8a-9609-11e6-92e6-4b5c264a1398.png)

@jamieu @emilyfildes do you have an idea of which items you want to show at the bottom of the page? I can create a json file with the list of urls to this items which will make it easy to modify later on.

@jamieu @emilyfildes @tobystokes let me know your thoughts/ideas

**Comment by tobystokes** [comment]
@emilyfildes ' list:

Lost Something Useful
http://collectionsonline-staging.eu-west-1.elasticbeanstalk.com/objects/smgc-objects-413845
 
Culpeper microscope
http://collectionsonline-staging.eu-west-1.elasticbeanstalk.com/objects/smgc-objects-444363
 
Replica of Isaac Newton’s reflecting telescope
http://collectionsonline-staging.eu-west-1.elasticbeanstalk.com/objects/smgc-objects-56834
 
Human skin tattooed with an eye (bit bleak?)
http://collectionsonline-staging.eu-west-1.elasticbeanstalk.com/objects/smgc-objects-77622
 
Model of an eye (bit bleak?)
http://collectionsonline-staging.eu-west-1.elasticbeanstalk.com/objects/smgc-objects-77088
 
Accident Emergency Case (i.e. this is an accident and needs fixing… tangential?)
http://collectionsonline-staging.eu-west-1.elasticbeanstalk.com/objects/smgc-objects-142861
 

But they definitely do need to be items with good images, so may need swapping later. But yep easy enough to do from a json for me or jamie

**Comment by SimonLab** [comment]
Thanks for the list @tobystokes :+1:

**Comment by SimonLab** [comment]
The information needed to display the related objects are:
- figure: attributes.multimedia.0.processed.mid.location
- caption: attributes.description || attributes.title || attributes.summary_title
- link: the link of the object see the @emilyfildes's list above

I don't think the related objects on the 404 object will change often, so instead of getting these values from elasticsearch we can just save them in the json object and update these values manually when we want to change the objects. This will render the page faster and won't generate any request to elasticsearch!

**Comment by jamieu** [comment]
Looks good, but leaving open to remind us to add images

**Comment by emilyfildes** [comment]
@SimonLab @tobystokes @jamieu 

Sorry for the delay on this - still waiting for the poster image (so keep open for that).

On reflection, it might be better for the related objects to stick with boarder categories rather than individual objects. How about something like.

Page not found

Sorry, the page you requested doesn't seem to exist.

If you were looking for something from our collection, try using the search box or explore some of the categories below:

[some categories]
- Materia Medica & Pharmacology (link to: /search?filter%5Bcategories%5D=Materia%20Medica%20%26%20Pharmacology&page%5Bsize%5D=50&page%5Btype%5D=search
- Locomotives and Rolling Stock (link to: /search?filter%5Bcategories%5D=Locomotives%20and%20Rolling%20Stock%20Components&page%5Bsize%5D=50&page%5Btype%5D=search)
- Art (link to: /search?filter%5Bcategories%5D=Art&page%5Bsize%5D=50&page%5Btype%5D=search)
- Computing & Data Processing (link to: /search?filter[categories]=Computing%20%26%20Data%20Processing)

I'll try and find some images for these - WDYT?

**Comment by jamieu** [comment]
See Emily's comment above..

**Comment by tobystokes** [comment]
could we make it 6 categories - to fill the whole row?

(i'll add them in when i process the images. If none are forthcoming  I could probably scrape together from the ones we used on home page)

**Comment by emilyfildes** [comment]
Of course:

- Photographic technology: (link to: /search?filter%5Bcategories%5D=Photographic%20Technology&page%5Bsize%5D=50&page%5Btype%5D=search)
- Scientific instruments and research (link to: /search?q=&filter%5Bcategories%5D=Scientific%20Instruments%20%26%20Research

I can send @tobystokes the railway poster image if that's helpful?
