### ISSUE TITLE
Only show 'notes' and 'brief biog' fields for People.

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#706]
http://collection.sciencemuseum.org.uk/api/people/cp2736

The naming on these is confusing I know, but we shouldn't be displaying the 'biography' field despite the name.

1) This should be the 'biography' field we display if available:

```
"note": [
        {
          "primary": true,
          "value": "1823 - founded by George Stephenson with his son Robert, ......"
        }
      ],
```

2) If we **don't have a `note` field** we should display the `"type": "brief biography",`

```
{
          "type": "brief biography",
          "value": "1823-1899, locomotive manufacturer, Newcastle-upon-Tyne, 
          England, British"
        }
```

We should **never display** `"type": "biography",`

**Comment by SimonLab** [comment]
@jamieu do you want to add a special field for the biography (called "biography"?) which will contain the right value extracted from "note" or "brief bio"  or do you want to still want to keep note and description (without the type briograpy) displayed? I think the description field might contain more information:
- brief biography
- web description
- biography (which will be deleted)
...
So it might be worth to keep displaying the description field maybe.

**Comment by jamieu** [comment]
Hi Somin,

Not sure if this is the answer to your question (or did you mean the API vs HTML?)

We just want one biography displayed, pulled from (in order).

- "note": (if available)
- "type": "brief biography", (if available, but not if we have "note:" above)
- blank (anything else)

We **never** want to display "type": "biography" in the HTML page. The reason we didn't normalised them down to a single value in the index is that we might want to access the data in the "type": "biography" later on / debugging. The Reason the names make no sense (ie. biog==notes and notes==biog is because that is how it is in the backend collection systems and we wanted to keep it consistent; in hindsight that might not have been the best idea but...). One day I will unpick all this, but now wasn't the time :-)

**Comment by jamieu** [comment]
Just to clarify this is only on the Mimsy derived people pages.

**Comment by SimonLab** [comment]
@jamieu thanks for the detail. Sorry I was thinking you were referring to the api page. At the moment the api page contains a bit more information displayed than the html view.
For the html view of the people we are already filtering the value for the biography. We are taking the notes if they exist otherwise we are taking the type="web description" from the description field, so we are excluding already the "biography" type. However I've just check and it seems than the "web description" type doesn't exist anymore in the index, I couldn't find any items with the search query:
```
{"query":{"constant_score":{"filter":{"term":{"description.type":"web description"}}}}}
```
I'll update this to the script to select "brief biography" instead.
The logic of the filter description is on [this file](https://github.com/TheScienceMuseum/collectionsonline/blob/42119a7a5e1dae13ba4308a877b4fa757722f632/lib/transforms/json-to-html-data.js#L126)

**Comment by jamieu** [comment]
The people pages have a slightly different format.

Basically we shoukd display "type:biog" as that's really an internal notes
field.

Sorry the naming is confusing!

**Comment by jamieu** [comment]
Sorry meant we *shouldn't* use notes:biog

**Comment by jamieu** [comment]
Having led you on a wild goose chase, I'm not going to close this ticket!

(I'm sure I was seeing the "type":"biography" field but maybe that was before something else got changed - the good news is it seems to be OK now!).
