### ISSUE TITLE
Fade SERP title vertically.

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#728]
I know I asked for it, but not sure the eclipses (...) are working - esp. with the diff char lengths on mobile vs desktop.

Can we look at how we can fade out the 3rd line of the title in CSS, but keep the date/category fixed/displayed below it? 

The category sometimes spans two lines, but I think we could problem get away with fading the second lien down or just moving the category/date down slightly.

Will need to revert the code back to displaying the full title (and just fading in CSS) once this is down.

<img width="307" alt="screen shot 2016-12-14 at 15 45 36" src="https://cloud.githubusercontent.com/assets/91365/21188862/a284bf46-c214-11e6-8ddd-d65b91737ef4.png">
<img width="343" alt="screen shot 2016-12-14 at 15 50 21" src="https://cloud.githubusercontent.com/assets/91365/21189121/89653328-c215-11e6-8d0d-9feaf8360cfd.png">

**Comment by tobystokes** [comment]
If we leave text untruncated in source, then I can set overflow as ellipsis or hidden in CSS, which gives us a bit more control over varying box sizes. e.g i could set max height of title to 2 lines-worth of whatever length is available. the whole white box fades out any further overflow already.

**Comment by SimonLab** [comment]
Thanks @tobystokes I will remove the truncated values

**Comment by tobystokes** [comment]
A bigger change, but fixes the root cause of the problem, and fits in better with the updated design: don't force the text area on the result cards to be a fixed (5-lines) height.

I'd need to use flex box grid for alignment (but that is fairly prevalent across the other new sites, with browser support at everything except IE9)

I'd still suggest an absolute max truncation on title for crazy ones (unless that is already enforced on input somewhere?) but it could be set much looser

**Comment by jamieu** [comment]
Sounds good, have added reminder in from to reduce the current truncation once you have pushed this change to master. 
https://github.com/TheScienceMuseum/collectionsonline/issues/891

**Comment by tobystokes** [comment]
still needs reimplementation for related results (over more than one line)
