### ISSUE TITLE
Query Phase Execution Exception : Result window is too large

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#735]
Getting a huge number of these errors in the logs (_post a Googlebot crawl_) - which is resulting in a significant number of HTTP 5.xx errors and EBS info messages to my phone.

One quick/sensible solution (I'd be happy with) might be to limit the maximum number of paginated results pages to 25 (or maybe 50 if were generous) as no one (other than a search bot) is going to click though to 25+ pages of paginated results. I guess the only danger is if this messes up the total counts (which would be very bad).

[for now I have increased the `index.max_result_window` setting but this doesn't seem like an ideal / long term solution]

```
[{\"range\":{\"lifecycle.birth.date.latest\":{\"lte\":1849}}},{\"range\":{\"lifecycle.creation.date.latest\":{\"lte\":1849}}}]}]}}]}}]}}}","statusCode":500,"response":"{\"error\":{\"root_cause\":[{\"type\":\"query_phase_execution_exception\",\"reason\":\"Result window is too large, from + size must be less than or equal to: [10000] but was [17500]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.\"}],\"type\":\"search_phase_execution_exception\",\"reason\":\"all shards failed\",\"phase\":\"query\",\"grouped\":true,\"failed_shards\":[{\"shard\":0,\"index\":\"smg\",\"node\":\"etzTDhTyQB6mK_gWpp8f9g\",\"reason\":{\"type\":\"query_phase_execution_exception\",\"reason\":\"Result window is too large, from + size must be less than or equal to: [10000] but was [17500]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.\"}}]},\"status\":500}"}
```

```
phase_execution_exception\",\"reason\":\"Result window is too large, from + size must be less than or equal to: [10000] but was [17500]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.\"}}]},\"status\":500}"}
    at /var/app/current/routes/search.js:69:42
    at /var/app/current/lib/search.js:131:12
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at respond (/var/app/current/node_modules/elasticsearch/src/lib/transport.js:308:9)
    at checkRespForFailure (/var/app/current/node_modules/elasticsearch/src/lib/transport.js:248:7)
    at HttpConnector.<anonymous> (/var/app/current/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
    at IncomingMessage.wrapper (/var/app/current/node_modules/elasticsearch/node_modules/lodash/lodash.js:4994:19)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
```

We could obviously just up the `index.max_result_window` setting - but not convinced that's really a good idea / solution.
http://stackoverflow.com/questions/35206409/elasticsearch-2-1-result-window-is-too-large-index-max-result-window

**Comment by SimonLab** [comment]
@jamieu I think the easier and quickest solution is to limit the pagination to the first few hundred pages. This should be easy to implement and it shouldn't break the count of the pagination. Elasticsearch 5 has now been released, I will try to see if this issue has been resolved on the new version.

**Comment by jamieu** [comment]
Let's do that then, if it's not too tricky 👍 

(although do double check the counts)

**Comment by jamieu** [comment]
I think we're still seeing an issue here, bit worrying with the HackDay round the corner.

<img width="1057" alt="screen shot 2017-02-01 at 16 46 54" src="https://cloud.githubusercontent.com/assets/91365/22516576/1ab9c7f4-e89e-11e6-82ff-cee38804462b.png">

**Comment by SimonLab** [comment]
@jamieu is it possible to get more/all logs possible which will help us to understand why the warning is showing. We need to see what trigger the requests and what type of requests make the server unhappy

**Comment by jamieu** [comment]
Sure, will upload them to Slack

**Comment by SimonLab** [comment]
I did a bit more research on the logs you send me @jamieu , during 2h (form 11h to 13h) I only could find 3 "Result window is too large" errors:

```
/search/objects {"filter[date[from]]":"1880","filter[date[to]]":"1950","page[size]":"50","page[type]":"search","page[number]":"1793"}

/search {"filter[date[from]]":"1831","filter[date[to]]":"1905","page[size]":"50","page[type]":"search","page[number]":"1145"}

/search/documents {"q":"","page[size]":"50","page[type]":"results-list","page[number]":"312"} 
```

We can see that the search query trying to access a page number > 150 which is trigger manuall as the UI limit the pagination to 150. However as the user-agent is not logged with the request it's difficult to say it was done by a bot (google or manually by someone, it might by us). I will have a look on how to display the user agent in the log. It's true that we could increase the memory and it might help a bit but it's not a long term solution. Unfortunately I don't think Elasticsearch manage to do deep pagination see your previous link on stack overflow (http://stackoverflow.com/questions/35206409/elasticsearch-2-1-result-window-is-too-large-index-max-result-window) and the explaination why deep pagination uses too much memory:

To understand why deep paging is problematic, let’s imagine that we are searching within a single index with five primary shards. When we request the first page of results (results 1 to 10), each shard produces its own top 10 results and returns them to the coordinating node, which then sorts all 50 results in order to select the overall top 10.
Now imagine that we ask for page 1,000—results 10,001 to 10,010. Everything works in the same way except that each shard has to produce its top 10,010 results. The coordinating node then sorts through all 50,050 results and discards 50,040 of them!
You can see that, in a distributed system, the cost of sorting results grows exponentially the deeper we page. There is a good reason that web search engines don’t return more than 1,000 results for any query.

A quick and easy solution to implement is to reduce the pagination on the backend to 150 (it's already done on the UI).

so:

- [ ] display user agent on the log
- [ ] force pagination to 150 max on the backend

**Comment by jamieu** [comment]
The problem with limiting in the backend is it disables users from
harvesting data from the site, which we'll be encouraging our colleagues in
the museum & academic sectors to do. Likewise aggregators of museum and
galley data will likely want to use the API to harvest our data.

Will have a think about the rest of your reply, but it's almost certainly
GoogleBot as to seems to happen at around the same time the site gets
crawled (you can sort of see a pattern if you look at the the requests
before and after the problem ones).
