### ISSUE TITLE
Absolutely vs relative paths for image locations in JSON?

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#778]
We seem to have switched to using absolute paths for the images, which is fine (_I'm guessing the carousel expects a full path and we didn't want to fork the code?_).

But just wanted to check:

- `"location_is_relative": true` is set even when we have an absolute path (see below) - if we're modifying the location in our JSON/API we should also update the `"location_is_relative' to reflect this or else it confuses consumers of our API. (**or even just remove it**).
- Is this consistent for all images? I previously noticed a mix of both, although now I obviously can't find an example with a relative path.

http://collection.sciencemuseum.org.uk/objects/co64127/phillips-economic-computer-analog-computer

**In our JSON API**

```
"processed": {
            "large": {
              "location": "http://smgco-images.s3.amazonaws.com/media/W/P/A/large_1995_0210__0001_.jpg",
              "location_is_relative": true,
```

**In the index**

```
"processed": {
"large": {
"location": "W/P/A/large_1995_0210__0001_.jpg",
"location_is_relative": true,
```

**Comment by iteles** [comment]
Task here is to drop `location_is_relative` from API.

**Comment by jrmhaig** [comment]
I realise that this issue is closed but I found it while confused about the `location_is_relative` flag (as @jamieu suggested it would be confusing). It appears that there was a PR to remove it (#784) but I still see it, and it appears to always be true regardless of whether the url is relative or not. I'm also confused about the suggestion (unless I am misunderstanding) that all urls for images are now absolute. I am consistently seeing the one for `large_thumbnail` as absolute but all the rest, such as `large`, `medium` and `zoom`, as relative. I don't know whether this will always be the case or if it has just a coincidence that this has been the case for all the records I have found. Can you please clarify.
