### ISSUE TITLE
Tidy up build/warning msgs

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#827]
Be good to have a little spring clean at some point to ensure the build doesn't throw any warnings.

1) (node) warning: possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit.

2) Error: reply interface called twice

https://api.travis-ci.org/jobs/209800586/log.txt?deansi=true

```
Debug: internal, implementation, error 
    Error: reply interface called twice
    at Object.exports.unique.exports.contain.exports.reachTemplate.exports.assert.condition [as assert] (/home/travis/build/TheScienceMuseum/collectionsonline/node_modules/hapi/node_modules/hoek/lib/index.js:736:11)
    at Function.internals.Reply.interface.internals.continue.internals.response (/home/travis/build/TheScienceMuseum/collectionsonline/node_modules/hapi/lib/reply.js:150:10)
    at Function.view
``` 

```
> collectionsonline@1.0.0 test:unit:tape /home/travis/build/TheScienceMuseum/collectionsonline
> istanbul cover -x **/bin/** tape 'test/**/*.test.js'
(node) warning: possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.addListener (events.js:239:17)
    at WriteStream.Readable.on (_stream_readable.js:680:33)
    at eos (/home/travis/build/TheScienceMuseum/collectionsonline/node_modules/good/node_modules/pumpify/node_modules/pump/node_modules/end-of-stream/index.js:66:9)
    at destroyer (/home/travis/build/TheScienceMuseum/collectionsonline/node_modules/good/node_modules/pumpify/node_modules/pump/index.js:28:3)
    at /home/travis/build/TheScienceMuseum/collectionsonline/node_modules/good/node_modules/pumpify/node_modules/pump/index.js:68:12
    at Array.map (native)
```

**Comment by shouston3** [comment]
It seems as though the `Error: reply interface called twice` message has stopped.

As for the memory leak messages, we should either:
+ Check back through the project and find the commit that caused the messages
+ Run specific groups of tests and see which ones are causing the problem

**Comment by shouston3** [comment]
Memory link culprits:
+ `test/autocomplete.test.js`

**Comment by shouston3** [comment]
So it seems that files containing the `testWithServer` are causing this memory leak error.

Fixing this would require about 2 hours of rewriting how the tests are running.

In particular the way that `test/helpers/test-with-server.js` runs and changing the way all of the tests which interact with this function (about 20 test files, but all very similar changes).

We would need to ensure to run each `withServer` type test inside of a test block instead of just executing them all at the same time on the top level of the file.

This memory leak is happening because when we run the tests containing `testWithServer`, all of these functions get called and it creates a lot of servers which are all waiting for a response.

If we wrap these in a `test` block these should be done individually and not cause this overflow of too many listeners being attached to the same object.

It is not currently very much of a problem, as this leak only happens in our tests and there is not a leak in the rest of our environment, but it would be good to fix at some point.

**Comment by jamieu** [comment]
makes sense, closing for now as part of housekeeping
